### ISSUE TITLE
Fix this thing

### ISSUE THREAD

**Issue by brotherlogic** [brotherlogic/goserver#51]
2017/05/24 17:41:36 Heartbeats beating
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1c pc=0x112074]

goroutine 1 [running]:
panic(0x3d79b8, 0x10920008)
        /usr/local/go/src/runtime/panic.go:500 +0x33c
google.golang.org/grpc.(*Server).Serve.func1(0x10cf4000, 0x0, 0x0)
        /home/simon/code/src/google.golang.org/grpc/server.go:445 +0xa0
panic(0x3d79b8, 0x10920008)
        /usr/local/go/src/runtime/panic.go:458 +0x454
google.golang.org/grpc.(*Server).Serve(0x10cf4000, 0x0, 0x0, 0x0, 0x0)
        /home/simon/code/src/google.golang.org/grpc/server.go:454 +0x1a8
github.com/brotherlogic/goserver.(*GoServer).Serve(0x1097b290)
        /home/simon/code/src/github.com/brotherlogic/goserver/goserverapi.go:82 +0x248
main.main()
        /home/simon/code/src/github.com/brotherlogic/discogssyncer/syncapi.go:119 +0x420

**Comment by brotherlogic** [comment]
Fixed
